version: '3'

services:
  frontend:
    build: ./vue-frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/src
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/src
